# Generated by Django 3.0 on 2023-08-31 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bin',
            old_name='desc',
            new_name='bin_name',
        ),
        migrations.RenameField(
            model_name='bin',
            old_name='create_by',
            new_name='update_by',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='create_by',
            new_name='update_by',
        ),
        migrations.RenameField(
            model_name='storage',
            old_name='create_by',
            new_name='update_by',
        ),
        migrations.RenameField(
            model_name='storage_type',
            old_name='create_by',
            new_name='update_by',
        ),
        migrations.RemoveField(
            model_name='bin',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='location',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='storage_type',
            name='create_at',
        ),
        migrations.AddField(
            model_name='bin',
            name='enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bin',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='location',
            name='location_name',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='mach_location_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='location_type', to='stock.Storage_Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='storage_type',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
