# Generated by Django 3.0 on 2023-08-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20230831_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='enable',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='enable',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='storage',
            name='enable',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
