# Generated by Django 3.0 on 2023-08-31 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0003_auto_20230831_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='update_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bin_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='location',
            name='update_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='location_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='storage',
            name='update_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='storage_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='storage_type',
            name='update_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='storage_type_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('iteme_code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_bin', to='stock.Bin')),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
