# Generated by Django 3.0 on 2023-08-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20230831_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='iteme_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
