# Generated by Django 3.0 on 2023-08-31 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20230831_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='iteme_code',
            new_name='item_code',
        ),
    ]
