# Generated by Django 3.0 on 2023-08-31 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0006_auto_20230831_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='WO',
            fields=[
                ('wo_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('qty', models.IntegerField(default=0)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='wo_item', to='stock.Item')),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='wo_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
