# Generated by Django 3.0 on 2023-09-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_wo_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='access_point',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
