# Generated by Django 3.0 on 2023-09-07 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0012_auto_20230907_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access_Point',
            fields=[
                ('point_code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('point_name', models.CharField(max_length=50)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='access_point_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
