# Generated by Django 3.0 on 2023-09-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_access_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='access_point',
        ),
        migrations.AddField(
            model_name='storage',
            name='access_point',
            field=models.ManyToManyField(to='stock.Access_Point'),
        ),
    ]
