# Generated by Django 3.0 on 2023-09-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_auto_20230907_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wo',
            name='item',
        ),
        migrations.AddField(
            model_name='wo',
            name='bin_code',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wo',
            name='bin_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wo',
            name='item_code',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
