# Generated by Django 3.0 on 2023-09-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_auto_20230907_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='wo',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
