# Generated by Django 3.0 on 2023-09-07 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_auto_20230907_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wo',
            name='access_point',
        ),
        migrations.RemoveField(
            model_name='wo',
            name='bin_code',
        ),
        migrations.RemoveField(
            model_name='wo',
            name='bin_name',
        ),
        migrations.RemoveField(
            model_name='wo',
            name='lift',
        ),
        migrations.RemoveField(
            model_name='wo',
            name='shelf',
        ),
        migrations.AddField(
            model_name='wo',
            name='bin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wo_bin', to='stock.Bin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wo',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wo_location', to='stock.Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wo',
            name='storage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wo_storage', to='stock.Storage'),
            preserve_default=False,
        ),
    ]
