# Generated by Django 3.0 on 2023-09-08 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0021_item_bin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wo',
            name='bin',
        ),
        migrations.RemoveField(
            model_name='wo',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='wo',
            name='item_code',
        ),
        migrations.RemoveField(
            model_name='wo',
            name='location',
        ),
        migrations.RemoveField(
            model_name='wo',
            name='storage',
        ),
        migrations.AddField(
            model_name='wo',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wo_item', to='stock.Item'),
            preserve_default=False,
        ),
    ]
