# Generated by Django 3.0 on 2023-09-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0022_auto_20230908_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='access_point',
            field=models.ManyToManyField(blank=True, null=True, to='stock.Access_Point'),
        ),
    ]
