# Generated by Django 3.0 on 2023-08-30 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('perm_wms', '管理系統權限'), ('perm_user_manage', '使用者管理')), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
